# Generated by Django 5.2.14 on 2026-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="sent", max_length=20)),
                ("message_preview", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-sent_at"],
            },
        ),
    ]
