# Generated by Django 5.2.14 on 2026-05-17 05:27

import apps.orders.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiber_type",
                    models.CharField(
                        choices=[
                            ("synthetic", "Sintética"),
                            ("natural", "Natural"),
                            ("mixed", "Mixta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_per_m2", models.DecimalField(decimal_places=2, max_digits=8)),
                ("effective_from", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Precio por m²",
                "verbose_name_plural": "Precios por m²",
                "ordering": ["-effective_from"],
                "get_latest_by": "effective_from",
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        default=apps.orders.models.generate_folio,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("agent_scheduled", "Agendado por Agente"),
                            ("technician_walkin", "Walk-in de Técnico"),
                            ("direct", "Directo"),
                        ],
                        default="agent_scheduled",
                        max_length=30,
                    ),
                ),
                ("pickup_address", models.TextField()),
                ("delivery_address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pickup_scheduled", "Recolección Agendada"),
                            ("picked_up", "Recolectado"),
                            ("received_at_spa", "Recibido en SPA"),
                            ("washing", "En Lavado"),
                            ("ready", "Listo para Entregar"),
                            ("delivery_scheduled", "Entrega Agendada"),
                            ("delivered", "Entregado"),
                        ],
                        default="pickup_scheduled",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Parcial"),
                            ("paid", "Pagado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Orden de Servicio",
                "verbose_name_plural": "Órdenes de Servicio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tratamiento",
                "verbose_name_plural": "Tratamientos",
            },
        ),
    ]
