# Generated by Django 5.2.14 on 2026-05-17 05:27

import apps.rugs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(default=1)),
                ("width_cm", models.DecimalField(decimal_places=1, max_digits=7)),
                ("height_cm", models.DecimalField(decimal_places=1, max_digits=7)),
                (
                    "fiber_type",
                    models.CharField(
                        choices=[
                            ("synthetic", "Sintética"),
                            ("natural", "Natural"),
                            ("mixed", "Mixta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recibido"),
                            ("washing", "En Lavado"),
                            ("ready", "Listo"),
                            ("delivered", "Entregado"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_m2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("odor_treatment", models.BooleanField(default=False)),
                (
                    "odor_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("stain_protector", models.BooleanField(default=False)),
                (
                    "stain_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("condition_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tapete",
                "verbose_name_plural": "Tapetes",
                "ordering": ["service_order", "index"],
            },
        ),
        migrations.CreateModel(
            name="RugPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("before", "Antes"),
                            ("after", "Después"),
                            ("damage", "Daño"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.ImageField(upload_to=apps.rugs.models.rug_photo_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Foto de Tapete",
                "verbose_name_plural": "Fotos de Tapetes",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
