# Generated by Django 5.2.14 on 2026-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("card", "Tarjeta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("at_scheduling", "Al Agendar"),
                            ("at_pickup", "En Recolección"),
                            ("at_spa", "En el SPA"),
                            ("at_delivery", "En Entrega"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-paid_at"],
            },
        ),
    ]
